name: release
on:
  push:
    tags:
        - '*.*.*'
env:
  DOTNET_VERSION: '7.0.x'
jobs:
  build-and-test:
    name: release-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Publish
      run: dotnet publish --configuration Release --no-build --verbosity normal --self-contained --output ./artifacts ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*
