name: release
on:
  push:
    tags:
        - '*.*.*'

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  publish:
    name: release-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    permissions:
        contents: write    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal ./SmallAreaFlowComp/SmallAreaFlowComp.sln

    - name: Publish linux
      run: dotnet publish --configuration Release --no-build --verbosity normal --self-contained --output ./artifacts/linux-x64 ./SmallAreaFlowComp/SmallAreaFlowComp.sln
      if: matrix.os == 'ubuntu-latest'

    - name: Publish windows
      run: dotnet publish --configuration Release --no-build --verbosity normal --self-contained --output ./artifacts/win-x64 ./SmallAreaFlowComp/SmallAreaFlowComp.sln
      if: matrix.os == 'windows-latest'

    - name: Publish macOS
      run: dotnet publish --configuration Release --no-build --verbosity normal --self-contained --output ./artifacts/macos-x64 ./SmallAreaFlowComp/SmallAreaFlowComp.sln
      if: matrix.os == 'macOS-latest'

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts/**/*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/**/*
